orbs: # declare what orbs we are going to use
  node: circleci/node@5.0.1

version: 2.1 # using 2.1 provides access to orbs and other features

jobs:
  install-node-example:
      docker:
        - image: 'cimg/base:stable'
      steps:
        - checkout
        - node/install:
            install-yarn: true
            node-version: '16.13'
        - run: node --version
        - npm-run-build: npm run build

workflows:
  deploy:
    jobs:
      - install-node-example